tabuada = int(input('Digite o número'))

print(f'Tabuada de {tabuada}')
print('-'*12)
print(f'1x{tabuada:3}={tabuada*1}')
print(f'2x{tabuada:3}={tabuada*2}')
print(f'3x{tabuada:3}={tabuada*3}')
print(f'4x{tabuada:3}={tabuada*4}')
print(f'5x{tabuada:3}={tabuada*5}')
print(f'6x{tabuada:3}={tabuada*6}')
print(f'7x{tabuada:3}={tabuada*7}')
print(f'8x{tabuada:3}={tabuada*8}')
print(f'9x{tabuada:3}={tabuada*9}')
print(f'10x{tabuada:2}={tabuada*10}')
print('-'*12)
